BasicCfg:
  GroupNumber:  "4"
  StageBlockNumber: "12"
  GameTheoryStop: "6"
  RevealStop: "9"
  InitNodesNumberinGroup: "4"
  NumberPrecision: "17"
ChainInfo:
  DBFile: "./storage/test_blockchain3.db"
  NodeDBFile: "./storage/"
  BlockSpeed: "1500" # 设定出块速度，单位ms
  TransactionSpeed: "100000" # 设定交易速度，单位us
TcpInfo:
  PBFTBaseAddress: "127.0.0.1"
  PBFTBasePortStart:  "13000"
  ClientAddr: "127.0.0.1:12999" # 虚拟的客户端正向监听交易地址
PrintControl:
  Commit: "false"
  MessageID: "false"
  PBFTMessagePrint: "false"