BasicCfg:
  GroupNumber:  "4"
  StageBlockNumber: "120"
  GameTheoryStop: "60"
  RevealStop: "90"
  InitNodesNumberinGroup: "3"
ChainInfo:
  DBFile: "./storage/test_blockchain.db"
  NodeDBFile: "./storage/"
  BlockSpeed: "5000" # 设定出块速度，单位ms
TcpInfo:
  PBFTBaseAddress: "127.0.0.1"
  PBFTBasePortStart:  "13000"