BasicCfg:
  GroupNumber:  "4"
  StageBlockNumber: "120"
  GameTheoryStop: "60"
  RevealStop: "90"
  InitNodesNumberinGroup: "3"
ChainInfo:
  DBFile: "./storage/test_blockchain.db"
  BlockSpeed: "2000" # 设定出块速度，单位ms